run:
  timeout: 5m

linters:
  enable:
    - revive
    - govet
    - staticcheck
    - errcheck
    - gosec
    - gocritic
    - nilerr

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
  gosec:
    severity: medium
    confidence: medium
